language: java
jdk: oraclejdk8
sudo: required
services: mysql
env: DB=mysql
before_script: mysql -e 'create database hostabroad;'; 
               mysql -u root --password="" < src/test/database.sql;
before_install: cd HostAbroadTests
#script: mvn surefire:test;

       

       

