language: java
jdk: oraclejdk8
sudo: required
services: mysql
env: DB=mysql
before_script: wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip;
               unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/;
               export CHROME_BIN=chromium-browser;
               mysql -e 'create database hostabroad;'; 
               mysql -u root --password="" < src/test/database.sql;
before_install: cd HostAbroadTests
script: mvn surefire:test -Dtest=UserTest.java;   #Ejecución de un solo test
        mvn surefire:test -Dtest=PairTest.java;
        mvn surefire:test -Dtest=TUserTest.java;
        mvn surefire:test -Dtest=FactoryCommandImpTest.java;

       

